builder:
  track: dev

labels:
  app-group: estafette-ci-extensions
  team: estafette-team
  language: golang

version:
  semver:
    major: 0
    minor: 1

stages:
  git-clone:
    image: extensions/git-clone:stable
    when:
      status == 'succeeded' &&
      server == 'estafette'

  build:
    image: golang:1.16.0-alpine3.13
    env:
      CGO_ENABLED: 0
      GOOS: linux
    commands:
    - go test ./...
    - go build -a -installsuffix cgo -ldflags "-X main.appgroup=${ESTAFETTE_LABEL_APP_GROUP} -X main.app=${ESTAFETTE_GIT_NAME} -X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./publish/${ESTAFETTE_GIT_NAME} .

  bake:
    image: extensions/docker:dev
    action: build
    container: git-clone
    inline: |
      FROM alpine:3.13

      LABEL maintainer="estafette.io" \
            description="The ${ESTAFETTE_GIT_NAME} component is an Estafette extension to clone a git repository for builds handled by Estafette CI"

      RUN apk add --update --no-cache \
          git \
          && rm -rf /var/cache/apk/*

      COPY ${ESTAFETTE_GIT_NAME} /

      ENV ESTAFETTE_LOG_FORMAT="console"

      ENTRYPOINT ["/${ESTAFETTE_GIT_NAME}"]
    repositories:
    - extensions
    path: ./publish

  check-container:
    parallelStages:
      check-efficiency:
        image: extensions/docker:dev
        action: dive
        container: git-clone
        repositories:
        - extensions

      vulnerability-scan:
        image: extensions/docker:dev
        action: trivy
        container: git-clone
        severity: low
        repositories:
        - extensions

  integration-test-override-max:
    image: extensions/git-clone:${ESTAFETTE_BUILD_VERSION}
    repo: estafette.io
    branch: main
    subdir: test

  integration-test-override-min:
    image: extensions/git-clone:${ESTAFETTE_BUILD_VERSION}
    repo: estafette.io
    # does not branch for now, since the default value is still master but not used by estaffette.io anymore
    branch: main

  delete-all-files:
    image: golang:1.16.0-alpine3.13
    commands:
    - ls -latr
    - rm -rf *
    - rm -rf .git
    - rm -rf .estafette.yaml
    - rm -rf .gitignore
    - ls -latr

  integration-test-override-any-public:
    image: extensions/git-clone:${ESTAFETTE_BUILD_VERSION}
    repo: https://github.com/golang/go
    branch: master
    subdir: .

  push-to-docker-hub:
    image: extensions/docker:dev
    action: push
    container: git-clone
    repositories:
    - extensions

  slack-notify:
    image: extensions/slack-build-status:dev
    workspace: estafette
    channels:
    - '#build-status'
    when:
      status == 'succeeded' ||
      status == 'failed'

releases:
  dev:
    triggers:
    - pipeline:
        name: self
        branch: .+
    stages:
      tag-container-image:
        image: extensions/docker:dev
        action: tag
        container: git-clone
        repositories:
        - extensions
        tags:
        - dev

  beta:
    stages:
      tag-container-image:
        image: extensions/docker:dev
        action: tag
        container: git-clone
        repositories:
        - extensions
        tags:
        - beta

      slack-notify:
        image: extensions/slack-build-status:dev
        workspace: estafette
        channels:
        - '#build-status'
        when:
          status == 'succeeded' ||
          status == 'failed'

  stable:
    stages:
      tag-container-image:
        image: extensions/docker:dev
        action: tag
        container: git-clone
        repositories:
        - extensions
        tags:
        - stable
        - latest

      slack-notify:
        image: extensions/slack-build-status:dev
        workspace: estafette
        channels:
        - '#build-status'
        when:
          status == 'succeeded' ||
          status == 'failed'

  nanoserver-1809-dev:
    builder:
      os: windows
      track: nanoserver-1809-dev
    clone: true
    stages:
      git-clone:
        image: extensions/git-clone:nanoserver-1809-stable

      build:
        image: estafette/golang:1.16.0-nanoserver-1809
        shell: cmd
        env:
          CGO_ENABLED: 0
          GOOS: windows
          GOARCH: amd64
        commands:
        - go build -v -ldflags "-X main.app=%ESTAFETTE_GIT_NAME% -X main.version=%ESTAFETTE_BUILD_VERSION% -X main.revision=%ESTAFETTE_GIT_REVISION% -X main.branch=%ESTAFETTE_GIT_BRANCH% -X main.buildDate=%ESTAFETTE_BUILD_DATETIME%" -o ./publish/%ESTAFETTE_GIT_NAME%.exe

      bake:
        image: extensions/docker:nanoserver-1809-dev
        action: build
        no-cache: true
        expand-variables: false
        container: git-clone
        repositories:
        - extensions
        dockerfile: Dockerfile.nanoserver-1809
        path: ./publish

      integration-test-override-max:
        image: extensions/git-clone:${ESTAFETTE_BUILD_VERSION}
        repo: estafette.io
        branch: main
        subdir: test

      push-to-docker-hub:
        image: extensions/docker:nanoserver-1809-dev
        action: push
        container: git-clone
        repositories:
        - extensions
        tags:
        - nanoserver-1809-dev
        pushVersionTag: false

  nanoserver-1809-beta:
    builder:
      os: windows
      track: nanoserver-1809-dev
    clone: true
    stages:
      git-clone:
        image: extensions/git-clone:nanoserver-1809-stable

      build:
        image: estafette/golang:1.16.0-nanoserver-1809
        shell: cmd
        env:
          CGO_ENABLED: 0
          GOOS: windows
          GOARCH: amd64
        commands:
        - go build -v -ldflags "-X main.app=%ESTAFETTE_GIT_NAME% -X main.version=%ESTAFETTE_BUILD_VERSION% -X main.revision=%ESTAFETTE_GIT_REVISION% -X main.branch=%ESTAFETTE_GIT_BRANCH% -X main.buildDate=%ESTAFETTE_BUILD_DATETIME%" -o ./publish/%ESTAFETTE_GIT_NAME%.exe

      bake:
        image: extensions/docker:nanoserver-1809-dev
        action: build
        no-cache: true
        expand-variables: false
        container: git-clone
        repositories:
        - extensions
        dockerfile: Dockerfile.nanoserver-1809
        path: ./publish

      integration-test-override-max:
        image: extensions/git-clone:${ESTAFETTE_BUILD_VERSION}
        repo: estafette.io
        branch: main
        subdir: test

      push-to-docker-hub:
        image: extensions/docker:nanoserver-1809-dev
        action: push
        container: git-clone
        repositories:
        - extensions
        tags:
        - nanoserver-1809-beta
        pushVersionTag: false

  nanoserver-1809-stable:
    builder:
      os: windows
      track: nanoserver-1809-dev
    clone: true
    stages:
      git-clone:
        image: extensions/git-clone:nanoserver-1809-stable

      build:
        image: estafette/golang:1.16.0-nanoserver-1809
        shell: cmd
        env:
          CGO_ENABLED: 0
          GOOS: windows
          GOARCH: amd64
        commands:
        - go build -v -ldflags "-X main.app=%ESTAFETTE_GIT_NAME% -X main.version=%ESTAFETTE_BUILD_VERSION% -X main.revision=%ESTAFETTE_GIT_REVISION% -X main.branch=%ESTAFETTE_GIT_BRANCH% -X main.buildDate=%ESTAFETTE_BUILD_DATETIME%" -o ./publish/%ESTAFETTE_GIT_NAME%.exe

      bake:
        image: extensions/docker:nanoserver-1809-dev
        action: build
        no-cache: true
        expand-variables: false
        container: git-clone
        repositories:
        - extensions
        dockerfile: Dockerfile.nanoserver-1809
        path: ./publish

      integration-test-override-max:
        image: extensions/git-clone:${ESTAFETTE_BUILD_VERSION}
        repo: estafette.io
        branch: main
        subdir: test

      push-to-docker-hub:
        image: extensions/docker:nanoserver-1809-dev
        action: push
        container: git-clone
        repositories:
        - extensions
        tags:
        - nanoserver-1809-stable
        pushVersionTag: false