FROM estafette/golang:1.15.6-windowsservercore-ltsc2019 as builder

FROM mcr.microsoft.com/windows/servercore:ltsc2019

COPY --from=builder C:/git C:/git

COPY estafette-extension-git-clone.exe C:/estafette-extension-git-clone.exe

ENV ESTAFETTE_LOG_FORMAT="console" \
    PATH="C:\git\cmd;C:\git\mingw64\bin;C:\git\usr\bin;$PATH"

USER ContainerAdministrator

ENTRYPOINT ["C:/estafette-extension-git-clone.exe"]